# Numpy assignment

Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde

In [ ]:
import numpy as np

def vandermonde_matrix(inpt, N = None, increasing = False):
    if N==None:
        N = len(inpt)
    if increasing:
        result = [[pow(elmnt, power) for power in range(0, N)] for elmnt in inpt]
        print(np.asanyarray(result))
    else:
        result = [[pow(elmnt, power) for power in range(N-1, -1, -1) ] for elmnt in inpt]
        print(np.asanyarray(result))  

In [2]:
inpt = [1,2,3,5]        
vandermonde_matrix(inpt,increasing = False)

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]


In [3]:
vandermonde_matrix(inpt, increasing = True)

[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]]





Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10

===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100

y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.
Question: Write a function to find moving average in an array over a window:

Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. 

In [6]:
def movingAverage(inputValue, k):
    z = 1
    output = np.convolve(inputValue, np.ones(k), 'valid') / k
    for i in output:
        print("y{0} = {1:.2f}".format(z, i))
        z += 1

In [7]:
inputValue = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k = 3
movingAverage(inputValue, k)

y1 = 5.00
y2 = 4.67
y3 = 5.67
y4 = 6.67
y5 = 9.67
y6 = 28.67
y7 = 49.33
y8 = 72.67
y9 = 84.00
y10 = 93.33
y11 = 116.33
